### ISSUE TITLE
Error: unable to find valid certification path to requested target

### ISSUE THREAD

**Issue by IT-Berater** [openskynetwork/opensky-api#10]
Hi,
no connect with JDK 1.7 or JDK1.8 on Mac OS X. 

This JUnit test:

```
/** credentials to test authenticated API calls **/
static final String USERNAME = "Thomas Wenzlaff";
static final String PASSWORD = "password";

// can only be tested with a valid account
	@Test
	public void testAuthGetStates() throws IOException, InterruptedException {
		if (USERNAME == null || PASSWORD == null) {
			System.out.println("WARNING: testAuthGetStates needs valid credentials and did not run");
			return;
		}

		OpenSkyApi api = new OpenSkyApi(USERNAME, PASSWORD);
		OpenSkyStates os = api.getStates(0, null);
		assertTrue("More than 1 state vector", os.getStates().size() > 1);
...

```
This is the stack trace:

> javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
> 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
> 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
> 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
> 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1497)
> 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:212)
> 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
> 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
> 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
> 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
> 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
> 	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:267)
> 	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:237)
> 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:148)
> 	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
> 	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
> 	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at org.opensky.api.OpenSkyApi$BasicAuthInterceptor.intercept(OpenSkyApi.java:54)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
> 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
> 	at okhttp3.RealCall.execute(RealCall.java:63)
> 	at org.opensky.api.OpenSkyApi.getResponse(OpenSkyApi.java:109)
> 	at org.opensky.api.OpenSkyApi.getOpenSkyStates(OpenSkyApi.java:149)
> 	at org.opensky.api.OpenSkyApi.getStates(OpenSkyApi.java:178)
> 	at TestOpenSkyApi.testAuthGetStates(TestOpenSkyApi.java:63)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 	at java.lang.reflect.Method.invoke(Method.java:497)
> 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
> 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
> 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
> 	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
> 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
> 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
> 	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
> 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
> 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
> 	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
> 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
> 	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
> 	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
> 	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:678)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
> 	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
> Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:387)
> 	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:292)
> 	at sun.security.validator.Validator.validate(Validator.java:260)
> 	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
> 	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
> 	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:124)
> 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1479)
> 	... 56 more
> Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
> 	at sun.security.provider.certpath.SunCertPathBuilder.build(SunCertPathBuilder.java:145)
> 	at sun.security.provider.certpath.SunCertPathBuilder.engineBuild(SunCertPathBuilder.java:131)
> 	at java.security.cert.CertPathBuilder.build(CertPathBuilder.java:280)
> 	at sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:382)
> 	... 62 more

Please help or fix!

Thomas

**Comment by fixje** [comment]
Hello Thomas,

we use Let'sEncrypt as our CA. It seems that the root certificates have been included in the JRE since [8u101](http://www.oracle.com/technetwork/java/javase/8u101-relnotes-3021761.html). Could you please check your JRE version?

Otherwise you could try to create a custom keystore as [described here](https://community.letsencrypt.org/t/will-the-cross-root-cover-trust-by-the-default-list-in-the-jdk-jre/134/13).

Markus

**Comment by IT-Berater** [comment]
java -version = 1.8.0_51

**Comment by IT-Berater** [comment]
Ok, jdk 1.8.0_131 works fine. Thanks.
