### ISSUE TITLE
Python string representation isn't accurate

### ISSUE THREAD

**Issue by L3viathan** [openskynetwork/opensky-api#2]
Both the `opensky_api.OpenSkyStates` and the `opensky_api.StateVector` behave contrary to expectations: Their string representation (`repr(...)`) looks like a dictionary, but they don't support subscripting (e.g. `TypeError: 'StateVector' object is not subscriptable`).

IMHO, `OpenSkyStates` and `StateVector` should either

- subclass `dict` and act like one
- [be replaced with simple dictionaries and not be custom objects at all](https://github.com/L3viathan/opensky-api)

or

- have a string representation that is more accurate or at least less deceptive. String representations should, if possible ["return a string that would yield an object with the same value when passed to eval(), otherwise [...] a string enclosed in angle brackets [...]"](https://docs.python.org/3/library/functions.html#repr).

**Comment by fixje** [comment]
13c38c38107fa2ba52db5b731579cdef32e33ea1 implements your third suggestion. Thanks!
