### ISSUE TITLE
I tried to run setup.py in cmd and by git but error occured as "No module named 'setuptools' "

### ISSUE THREAD

**Issue by AmberCXX** [openskynetwork/opensky-api#25]
Traceback (most recent call last):
  File "setup.py", line 2, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'

**Comment by nbroad1881** [comment]
Run `pip install setuptools`

Then change directories to the same directory as  `setup.py` and do `pip install -e .`
