### ISSUE TITLE
Timeout Errors

### ISSUE THREAD

**Issue by Wcrochet** [openskynetwork/opensky-api#29]
Over the past week I have been getting timeout errors whenever I try to pull information from the API. I have had no issues prior to this so I was wondering if something is going on with OpenSky?

This is part of the error I typically get:
  File "C:\Users\wcrochet\Anaconda3\envs\untitled\lib\site-packages\requests\adapters.py", line 529, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='opensky-network.org', port=443): Read timed out. (read timeout=15.0)

**Comment by Jxck-S** [comment]
Add a try statement `then it wont fail if your looping then itl try again. 
try:
     planeData = opens_api.get_states(time_secs=0, icao24=TRACK_PLANE.lower())
except:
     print("OpenSky Error")
`

**Comment by elementzero23** [comment]
The solution works fine in Python. Any hints on how to get around `java.net.SocketTimeoutException: Read timed out` in Java?

**Comment by Jxck-S** [comment]
> The solution works fine in Python. Any hints on how to get around `java.net.SocketTimeoutException: Read timed out` in Java?

You can use a try-catch in Java https://www.w3schools.com/java/java_try_catch.asp in the catch put the exception type. I'm not very good with Java but that should work.

**Comment by masorx** [comment]
Should be much better in recent times but can still happen under load, needs to be handled client-side.
