### ISSUE TITLE
SMTP connect failed when creating an account

### ISSUE THREAD

**Issue by yxiao92** [openskynetwork/opensky-api#30]
Hi,

I was trying to create an account to access the API.

I receive this error after completing the form and hitting the 'Register' button:

`SMTP connect failed https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting`

I couldn't receive my activation email as a result.

Can you fix this issue?

**Comment by hyperific** [comment]
This happened to me today as well

**Comment by foxtrotmike** [comment]
Same issue here. Unable to register for academic research and no email received for my academic email account.
