### ISSUE TITLE
Accessing API data with C# .NET Framework

### ISSUE THREAD

**Issue by jasonTheHuman2101** [openskynetwork/opensky-api#32]
Hello!
Does anybody know of a way to access the data with C#? I'm able to get a raw JSON string, but i'm unable to parse it. i've tried parsing it with JSON.NET, and went through some other methods, all spitting out various errors.
Anybody know of a way to get the data in a way i can use it? Any insight would be appreciated!
JCS

**Comment by schulz3000** [comment]
Hi @jasonTheHuman2101 
some time ago I created a C# wrapper for the opensky api.
You can find it here: https://github.com/schulz3000/OpenSkyNet
If you find any issue feel free to open a ticket.
