### ISSUE TITLE
CORS header on response?

### ISSUE THREAD

**Issue by Arkanic** [openskynetwork/opensky-api#34]
I've heard that the API has CORS support, but in practise i'm not getting a Content-Allow-Origin header. Can anyone give me a heads up?

Thanks

**Comment by Arkanic** [comment]
nevermind, figured it out

**Comment by benlansdell** [comment]
I have the same issue... I don't see it in the response header. How did you figure it out?

**Comment by Arkanic** [comment]
@benlansdell I wouldn't really call it solving...

I just set up a simple server that acted as a sort of proxy to the API, except that it had CORS response headers. The client would contact the server asking for something, and the server would in turn ask the opensky API for the result, which it would then send back to the client

**Comment by benlansdell** [comment]
Hah yes, that's exactly what I ended up doing too.... Oh well. Thanks anyway @Arkanic
