### ISSUE TITLE
Doesn't load data

### ISSUE THREAD

**Issue by Mohammadreza20** [openskynetwork/opensky-api#35]
I work with python and need the data, I have two problems 1_the download of data is very slow (speed internet = 20 megabits per sec) 2_ from yesterday the data doesn't load for me, why?

my code:

```python

request = (
    f"""-q select time,icao24,callsign,baroaltitude,lastposupdate,lat,lon from state_vectors_data4
    where baroaltitude <= 10000 and baroaltitude >= 8000
    and time>={start_time} and time<={end_time}
    and lat>={lat_min} and lat<={lat_max}
    and lon>={lon_min} and lon<={lon_max} limit 100
    
    """
)


p = paramiko.SSHClient()
p.set_missing_host_key_policy(paramiko.AutoAddPolicy())
p.connect( "data.opensky-network.org", 2230, username = username, password = password, look_for_keys=False, allow_agent=False, compress=True)
stdin, stdout, stderr = p.exec_command(request)
stdout.readlines()
```

**Comment by masorx** [comment]
We can't change the download speed - the system is not intended to download large amounts of data. You can do typical calulcations right on the database. Second issue was just temporary hickup.

**Comment by q-wertz** [comment]
You can maybe also speed up the query by using the `hour` column as stated [here](https://opensky-network.org/data/impala) (section `3. Boosting Query Performance`)
