### ISSUE TITLE
`get_states` does not seem to work on historical time points

### ISSUE THREAD

**Issue by bdnorman** [openskynetwork/opensky-api#54]
`api.get_states()` works as expected however if I provide it a prior timepoint (even an hour back) it returns `None` (example: `api.get_states(time_secs=1682089728)`).

Digging into it a bit:
```
r = requests.get(
            "{0:s}{1:s}".format(api._api_url, '/states/all'),
            auth=api._auth,
            params=params,
            timeout=15.00,
        )
```
returns a `400` with no reason.

Am I doing something wrong or is this expected behavior?

**Comment by bdnorman** [comment]
Ah I'm seeing `Historical data more than 1 hour ago can only be retrieved with /states/own`

**Comment by BastiaanGrisel** [comment]
So, is there a way to access this historical data?

**Comment by masorx** [comment]
https://opensky-network.org/data/impala
