### ISSUE TITLE
SMTP issue when registering

### ISSUE THREAD

**Issue by macster9** [openskynetwork/opensky-api#58]
I have tried signing up a few times but there is an SMTP connection error (https://github.com/PHPMailer/wiki/Troubleshooting - identical to previous issue) and "a message has been sent to admin". Have tried 3 different times with 3 different emails.

Did I do something wrong or can this be resolved server end?

**Comment by macster9** [comment]
Identical to issue #30

**Comment by foxtrotmike** [comment]
Same issue here. Unable to register for academic research and no email received for my academic email account.

**Comment by shadowwider** [comment]
Same issue here. Can't get email

**Comment by leguidomanfredi** [comment]
Same issue here. 
While you fix the issue, is it possible to have an email or some communication mean to register?

**Comment by alexey-milovidov** [comment]
The same issue - I cannot create an account.
