### ISSUE TITLE
Question: Are you planing to allow cross-origin requests?

### ISSUE THREAD

**Issue by guilhermevrs** [openskynetwork/opensky-api#6]
Hello,

First of all, great job with the API. It is really awesome.

I have a small question, if I want to create small demos using javascript for example, I would need to make cross-origin requests.

Are you planning to allow that in an early future?

Thanks in advance

**Comment by fixje** [comment]
Thanks for your feedback! We do our best to provide even more information in the future.

CORS doesn't come for free. We need to think about the implications on security. As we currently have a lot of other things going on, I am afraid that this won't happen any time soon.

**Comment by badazz91** [comment]
>(...), if I want to create small demos using javascript for example, I would need to make cross-origin requests.

Same here for me. Supporting cross-origin-requests would be a big help for me as well.

**Comment by fixje** [comment]
We've just enabled it. Have fun!
